POST https://localhost:1116/connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded

{
    "grant_type": "cli3ent_credentials",
    "client_id": "m32m.client",
    "client_secret": "511536EF-F270-4058-80CA-1C89C192F69A",
    "scope": "scope1"
}