@baseUrl = https://localhost:1115

# @name loginClient
POST {{baseUrl}}/connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded
Accept: application/json

grant_type=client_credentials
&client_id=m2m.client
&client_secret=511536EF-F270-4058-80CA-1C89C192F69A
&scope=scope1 IdentityServerApi

###
@clientAuthToken = {{loginClient.response.body.access_token}}

# @name login
POST {{baseUrl}}/connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded
Accept: application/json

grant_type=PKCE
&client_id=demo_api_no_PKCE
&client_secret=secret
&scope=api1
###
@authToken = {{login.response.body.access_token}}

# @name DoNotUseImplicitLogin
POST {{baseUrl}}/connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded
Accept: application/json

grant_type=authorization_code
&client_id=ro.client
&scope=api1
###
@authToken = {{DoNotUseImplicitLogin.response.body.access_token}}

# @name ResourceOwnerPasswordLogin
POST {{baseUrl}}/connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded
Accept: application/json

grant_type=password
&client_id=ro.client
&client_id=ro.client
&client_secret=secret
&username=bob
&password=Pass123$
&scope=api1
###
@passwordAuthToken = {{ResourceOwnerPasswordLogin.response.body.access_token}}

# @name DiagnosticsAPI
POST {{baseUrl}}/Diagnostics/IndexApi HTTP/1.1
Authorization: Bearer {{ResourceOwnerPasswordLogin}}
Content-Type: application/json

###
# @name Diagnostics
POST {{baseUrl}}/Diagnostics/Index HTTP/1.1
Authorization: Bearer {{passwordAuthToken}}
Content-Type: application/json